#!/usr/bin/env Rscript
#
# testdata_bcdata.R
#
# Reproduce the bundled 10m test DEM without the bcfishpass database.
# Uses bcdata (Python CLI by Simon Norris) to fetch the 25m provincial DEM
# from BC Data Catalogue WCS, then resamples to 10m with bilinear
# interpolation — the same approach used by bcfishpass habitat_lateral.
#
# This is an internal reproducibility reference, not user-facing.
# The bundled test data in inst/testdata/ is generated by testdata.R
# (which reads from the bcfishpass BULK DEM). This script documents
# an alternative path that doesn't require the database.
#
# Prerequisites:
#   - Python with bcdata installed: pip install bcdata
#   - R packages: terra, sf
#
# Pattern from:
#   bcfishpass/model/03_habitat_lateral/valley_confinement.py
#     bcdata.get_dem(bounds, path, as_rasterio=True, align=True)
#     gdaldem slope -p dem.tif slope.tif
#
# Output:
#   data-raw/dem_bcdata_25m.tif  — raw 25m DEM from BC Data Catalogue
#   data-raw/dem_bcdata_10m.tif  — resampled to 10m (bilinear)
#   data-raw/slope_bcdata_10m.tif — percent slope from 10m DEM

library(terra)
library(sf)

# --- Test area extent (same as inst/testdata/) ---
# Neexdzii Kwah near Topley, BC Albers EPSG:3005
xmin <- 975728
xmax <- 983728
ymin <- 1054058
ymax <- 1060538

out_dir <- here::here("data-raw")

# --- Download 25m DEM via bcdata CLI ---
# bcdata get-dem fetches from BC Data Catalogue WCS
# bounds format: xmin,ymin,xmax,ymax in EPSG:3005
dem_25m_path <- file.path(out_dir, "dem_bcdata_25m.tif")

if (!file.exists(dem_25m_path)) {
  bounds <- paste(xmin, ymin, xmax, ymax, sep = ",")
  cmd <- paste(
    "bcdata", "get-dem",
    "--bounds", bounds,
    "--src_crs", "EPSG:3005",
    "--dst_crs", "EPSG:3005",
    dem_25m_path
  )
  message("Downloading 25m DEM via bcdata...")
  message("  Command: ", cmd)
  system(cmd)
} else {
  message("25m DEM already exists: ", dem_25m_path)
}

# --- Resample to 10m (bilinear, matching bcfishpass pattern) ---
dem_10m_path <- file.path(out_dir, "dem_bcdata_10m.tif")

message("Resampling 25m -> 10m (bilinear)...")
dem_25m <- terra::rast(dem_25m_path)

# Create 10m template matching the test data extent
template_10m <- terra::rast(
  xmin = xmin, xmax = xmax,
  ymin = ymin, ymax = ymax,
  resolution = 10,
  crs = "EPSG:3005"
)

dem_10m <- terra::resample(dem_25m, template_10m, method = "bilinear")
terra::writeRaster(dem_10m, dem_10m_path, overwrite = TRUE)

# --- Derive slope (percent, matching gdaldem slope -p) ---
slope_10m_path <- file.path(out_dir, "slope_bcdata_10m.tif")

message("Deriving percent slope...")
slope_deg <- terra::terrain(dem_10m, "slope", unit = "degrees")
slope_pct <- tan(slope_deg * pi / 180) * 100
terra::writeRaster(slope_pct, slope_10m_path, overwrite = TRUE)

# --- Summary ---
message("\nOutputs:")
message("  25m DEM: ", dem_25m_path, " (",
        round(file.size(dem_25m_path) / 1e6, 1), " MB)")
message("  10m DEM: ", dem_10m_path, " (",
        round(file.size(dem_10m_path) / 1e6, 1), " MB)")
message("  Slope:   ", slope_10m_path, " (",
        round(file.size(slope_10m_path) / 1e6, 1), " MB)")
message("  Extent:  ", paste(xmin, xmax, ymin, ymax, sep = ", "), " (EPSG:3005)")
message("  Res:     ", paste(res(dem_10m), collapse = " x "), " m")
